### ISSUE TITLE
With 2.2.1 mypy complains that 'google.cloud' is missing 'storage' attribute

### ISSUE THREAD

**Issue by asfaltboy** [googleapis/python-cloud-core#166]
This may be related to recent changes in core and this issue:
- googleapis/python-storage#393

#### Environment details

  - OS type and version: MacOS 11.6
  - Python version: cpython 3.10
  - pip version: 21.3.1
  - `google-cloud-core` version: 2.2.1

#### Steps to reproduce

  1. `pip install google-cloud-core google-cloud-storage mypy`
  2. create python file as below
  3. `mypy .` gets `Module 'google.cloud' has no attribute 'storage'`
  4. To work around, try `pip install google-cloud-core<2`
  5. `mypy .` returns no errors

#### Code example

```python
from google.cloud import storage
```

**Comment by busunkim96** [comment]
Hi @asfaltboy,

`google-cloud-storage` does not currently have any type hints as they are in the process of removing 2.7 support.

If the only error you are seeing is on that line, the best course of action is to skip type checking for `google-cloud-storage`. I believe you will still be able to type check code in other google-cloud libraries that do ship types.

```py
from google.cloud import storage  # type: ignore
from google.cloud import ...
```

**Comment by kojiromike** [comment]
If you don't want to use `type: ignore` and want to take advantage of types as they emerge, mypy will not complain about

```
import google.cloud.storage as storage
```
