### ISSUE TITLE
Infer project from credentials if not passed explicitly

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-cloud-core#27]
Split off from #17

See also: https://github.com/googleapis/python-datastore/issues/74
See also: https://github.com/googleapis/python-storage/issues/177

In a "blank slate" design, I would argue that the credentials' project should supersede the one present in the environment.  However, for backward compatibility, we need to use the credentials' project only if the environment variable is not set.   So the order should follow the pattern from `google.auth.default` when inferring project ID:

- Explicit project ID passed to client constructor
- Project ID set in `GOOGLE_CLOUD_PROJECT` envvar
- Project ID from credentials, if present
- Project ID from SDK
- Project ID from GAE
- Project ID from GCE

**Comment by tseaver** [comment]
In the case where credentials are discovered for us, `google.auth.default()` already falls back to the project in the credentials.  E.g.:

```bash
$ unset GOOGLE_CLOUD_PROJECT GCLOUD_PROJECT
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account.json
$ grep project_id /path/to/service_account.json
    "project_id": "some-project-123"
$ python
>>> from google.auth import default
>>> credentials, project = default()
>>> project
'some-project-123'
>>> from google.cloud.client import ClientWithProject
>>> client = ClientWithProject()
>>> client.project
'some-project-123'
```

So, the case we need to cover for this feature is when the user has passed in explicit service account credentials, but not an explicit project ID, e.g. (this won't currently work):

```bash
$ unset GOOGLE_CLOUD_PROJECT GCLOUD_PROJECT GOOGLE_APPLICATION_CREDENTIALS
$ python
>>> from google.oauth2.service_account import Credentials
>>> credentials = Credentials.from_service_account_file("/path/to/service_account.json")
>>> from google.cloud.client import ClientWithProject
>>> client = ClientWithProject(credentials=credentials)  # currently raises
```

**Comment by dhermes** [comment]
Is there a reason `CLOUDSDK_CORE_PROJECT` isn't also supported?

I made it here via https://github.com/googleapis/python-cloud-core/blob/e5fb3ea79ea70d538a97c758a33d0b3ab7d1182c/google/cloud/client/__init__.py#L252-L260
