### ISSUE TITLE
Clients do not clean up Requests sessions

### ISSUE THREAD

**Issue by akx** [googleapis/python-cloud-core#64]
#### Environment details

  - OS type and version: macOS
  - Python version: 3.9
  - `google-cloud-core` version: 1.4.3
  - `google-cloud-storage` version: 1.33.0 (since it's related)

#### Steps to reproduce

This is a sibling issue to https://github.com/googleapis/google-auth-library-python/issues/658 and as such the below is similar to that issue.

[Py.test 6.2 enables hard errors on unhandled thread exceptions and resource errors](https://docs.pytest.org/en/stable/usage.html#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions) such as leaking sockets/SSL sockets/FDs/.... I've spent the last couple hours debugging various

```
ResourceWarning: unclosed <ssl.SSLSocket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.23', 60522), raddr=('216.58.207.202', 443)>
```

When initiating (e.g.) a [`google-cloud-storage` storage client](https://github.com/googleapis/python-storage) with e.g.

```python
        creds = self.get_client_credentials()
        return storage.Client(project=creds.project_id, credentials=creds)
```

the client object is initialized with no explicit `_http` object, and the [default code path](https://github.com/googleapis/python-cloud-core/blob/d01c825d4b7638e76d9d2883baba5a91c884e310/google/cloud/client.py#L172-L184) is run, creating a new `requests.Session()` that will be _eventually_ GC'd but is otherwise not [`close()`d](https://requests.readthedocs.io/en/latest/api/#requests.Session.close), leading to the above warning (and a dropped connection and socket, which may have implications down the line).

Since `google.core.client.Client` doesn't implement e.g. the context manager protocol or `close()`, there's no officially sanctioned way to clean up that session; for a storage Client, I subclassed one as a workaround but it would be nice if Clients had an official `close()`.

```python
        class CloseableStorageClient(storage.Client):
            def __enter__(self):
                return self

            def __exit__(self, *args):
                self._http.close()
```

#### Resolution suggestion

At the very least, add `close()` to `Client`s; by default it should probably only be something like
  ```python
  def close(self):
      if self._http_internal:
          self._http_internal.close()
  ```
, the semantics being a best-effort cleanup of resources allocated by the client, but not irreversible finalization.

With this, `Client`s could be used with [`contextlib.closing()`](https://docs.python.org/3.9/library/contextlib.html#contextlib.closing). Additionally, one could add a minimal context management protocol implementation á la

```python
            def __enter__(self):
                return self

            def __exit__(self, *args):
                self.close()
```

If you folks think this is a good way to go, I can certainly write the PR :)

cc @busunkim96 (for having triaged the other issue).

**Comment by busunkim96** [comment]
Thanks @akx!

CC @crwilcox as a `google-cloud-storage`  owner.

We've talked about a `close()` method for the gapic clients. Ideally the behavior will be similar in both the generated and handwritten clients. https://github.com/googleapis/gapic-generator-python/issues/575

**Comment by crwilcox** [comment]
Cc @frankyn @andrewsg

**Comment by tseaver** [comment]
FWIW, I'd argue that this is a feature request, rather than a bug (not that I'm opposed to adding it).

**Comment by tseaver** [comment]
I'd also suggest that the existence of `contextlib.closing` makes it unnecessary to add our own `__enter__` / `__exit__` methods.
